#!/usr/bin/env python3

import re
import subprocess

import click


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
@click.version_option(
    prog_name="manage",
    message="%(prog)s %(version)s: Manage all the things."
)
def cli():
    pass


@cli.command()
def release():
    """Prepare a release."""
    readme = open("README.md").read()
    child = subprocess.Popen(["ipfs", "add", "-Q", "-r", "ipfessay"], stdout=subprocess.PIPE)
    new_hash = child.stdout.read().decode("utf8").strip()
    readme = re.sub(r"/ipfs/[a-zA-Z0-9]*?\n", r"/ipfs/%s\n" % new_hash, readme, count=2)
    readme = re.sub(r"(ipfs pin add) [a-zA-Z0-9]+", r"\1 %s" % new_hash, readme)
    open("README.md", "w").write(readme)
    print("Released %s" % new_hash)
    child = subprocess.Popen(["ipfs", "name", "publish", "--key=ipfessay", new_hash], stdout=subprocess.PIPE)
    ipns_out = child.stdout.read().decode("utf8").strip()
    ipns = re.search("(\w+)+\:", ipns_out).groups(1)[0]
    print("Linked IPNS name: %s" % ipns)


def main():
    return cli(obj={})


if __name__ == "__main__":
    main()
